### ISSUE TITLE
OutOfMemory exception when accessing StringFileInfo of oleaut32.dll

### ISSUE THREAD

**Issue by rosenqui-cysiv** [secana/PeNet#199] opened 2021-07-30 16:03 UTC
`StringFileInfo.ReadChildren` gets itself into an infinite loop when trying to access the string table of `oleaut32.dll`.

This appears to be because it hits a segment of length 0, so the loop keeps adding the same zero-length item and never exits since the offset never moves.

Note that this is the 64-bit `oleaut32.dll` of length 831544 from Windows 10 20H2:

```
> [System.Diagnostics.FileVersionInfo]::GetVersionInfo("c:\windows\system32\oleaut32.dll") | fl *

FileVersionRaw     : 10.0.19041.985
ProductVersionRaw  : 10.0.19041.985
Comments           :
CompanyName        : Microsoft Corporation
FileBuildPart      : 19041
FileDescription    : OLEAUT32.DLL
FileMajorPart      : 10
FileMinorPart      : 0
FileName           : c:\windows\system32\oleaut32.dll
FilePrivatePart    : 985
FileVersion        : 10.0.19041.985 (WinBuild.160101.0800)
InternalName       : OLEAUT32.DLL
IsDebug            : False
IsPatched          : False
IsPrivateBuild     : False
IsPreRelease       : False
IsSpecialBuild     : False
Language           : English (United States)
LegalCopyright     : © Microsoft Corporation. All rights reserved.
LegalTrademarks    :
OriginalFilename   : OLEAUT32.DLL
PrivateBuild       :
ProductBuildPart   : 19041
ProductMajorPart   : 10
ProductMinorPart   : 0
ProductName        : Microsoft® Windows® Operating System
ProductPrivatePart : 985
ProductVersion     : 10.0.19041.985
SpecialBuild       :
```

**Comment by secana** [comment] 2021-08-01 09:39
I'll have a look. Thanks for reporting the bug!

**Comment by secana** [comment] 2021-08-01 11:43
@rosenqui-cysiv Could you check if the problem still exists in 2.6.4-pre1?

**Comment by secana** [comment] 2021-08-04 10:39
Fixed in 2.6.4

**Closed by secana** 2021-08-04 10:39 UTC

**Comment by rosenqui-cysiv** [comment] 2021-08-09 12:12
Sorry @secana - I was on vacation and just returned now. For what it's worth, I was able to reproduce it with this 2-liner:
```c#
var peFile = new PeFile(@"C:\Windows\System32\oleaut32.dll");
var stringTable = peFile.Resources?.VsVersionInfo.StringFileInfo.StringTable;
```

**Comment by secana** [comment] 2021-08-11 13:29
Does the issue still exists in the latest PeNet version (2.6.4)? I'm not able to reproduce the problem anymore with that version.
